version: '3.8'

services:
  yapi-mcp-server:
    image: yukaifan/yapi-mcp-server
    container_name: yapi-mcp-server
    ports:
      - "8888:8888"
    volumes:
      - ./application-mcp.yml:/workspace/application-mcp.yml
    restart: unless-stopped
