spring:
  ai:
    mcp:
      server:
        name: yapi-mcp-server
        version: 1.0.0
        request-timeout: 60
        instructions: "This service provides some tool for querying API documentation from Yapi"
        capabilities:
          prompt: false
          resource: false
          completion: false
  profiles:
    active: mcp
server:
  port: 8888